### ISSUE TITLE
cabal install error 

### ISSUE THREAD

**Issue by gabin22** [jprupp/haskoin-wallet#2]
gabin@BlueDisk:~/develop/haskoin/haskoin-wallet$ cabal install
Resolving dependencies...
Configuring haskoin-wallet-0.6.0.0...
Building haskoin-wallet-0.6.0.0...
Failed to install haskoin-wallet-0.6.0.0
Build log ( /home/gabin/.cabal/logs/haskoin-wallet-0.6.0.0.log ):
cabal: Entering directory '.'
Configuring haskoin-wallet-0.6.0.0...
Building haskoin-wallet-0.6.0.0...
Preprocessing library haskoin-wallet-0.6.0.0...
[ 5 of 10] Compiling Network.Haskoin.Wallet.DetailedTx ( src/Network/Haskoin/Wallet/DetailedTx.hs, dist/build/Network/Haskoin/Wallet/DetailedTx.o )

src/Network/Haskoin/Wallet/DetailedTx.hs:168:41: error:
    • Couldn't match type ‘Either LString Address’ with ‘Address’
      Expected type: Address -> Either String Address
        Actual type: Either LString Address -> Either String Address
    • In the first argument of ‘(.)’, namely ‘eitherString’
      In the second argument of ‘(>=>)’, namely
        ‘eitherString . outputAddress net’
      In the expression:
        decodeTxOutSO >=> eitherString . outputAddress net
    |
168 | decodeTxOutAddr net = decodeTxOutSO >=> eitherString . outputAddress net
    |                                         ^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:168:56: error:
    • Couldn't match type ‘Maybe’ with ‘(->) ScriptOutput’
      Expected type: ScriptOutput -> Address
        Actual type: Maybe Address
    • Possible cause: ‘outputAddress’ is applied to too many arguments
      In the second argument of ‘(.)’, namely ‘outputAddress net’
      In the second argument of ‘(>=>)’, namely
        ‘eitherString . outputAddress net’
      In the expression:
        decodeTxOutSO >=> eitherString . outputAddress net
    |
168 | decodeTxOutAddr net = decodeTxOutSO >=> eitherString . outputAddress net
    |                                                        ^^^^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:168:70: error:
    • Couldn't match expected type ‘ScriptOutput’
                  with actual type ‘Network’
    • In the first argument of ‘outputAddress’, namely ‘net’
      In the second argument of ‘(.)’, namely ‘outputAddress net’
      In the second argument of ‘(>=>)’, namely
        ‘eitherString . outputAddress net’
    |
168 | decodeTxOutAddr net = decodeTxOutSO >=> eitherString . outputAddress net
    |                                                                      ^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:206:51: error:
    • Couldn't match type ‘Address’ with ‘Network’
      Expected type: [(Network, Satoshi)]
        Actual type: [(Address, Satoshi)]
    • In the second argument of ‘fmap’, namely
        ‘(Map.assocs detailedTxOutbound)’
      In the first argument of ‘(<>)’, namely
        ‘fmap (addrFormat negate) (Map.assocs detailedTxOutbound)’
      In the second argument of ‘(<>)’, namely
        ‘fmap (addrFormat negate) (Map.assocs detailedTxOutbound)
           <> [nonStdRcp]’
    |
206 |             [feeKey] <> fmap (addrFormat negate) (Map.assocs detailedTxOutbound) <>
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:232:35: error:
    • Couldn't match type ‘Address’ with ‘Network’
      Expected type: [(Network, Natural)]
        Actual type: [(Address, Natural)]
    • In the second argument of ‘fmap’, namely
        ‘(Map.assocs $ Map.map fst detailedTxInbound)’
      In the second argument of ‘(<>)’, namely
        ‘fmap (addrFormat id) (Map.assocs $ Map.map fst detailedTxInbound)’
      In the second argument of ‘($)’, namely
        ‘[if Map.size detailedTxInbound > 1 then
              keyDoc 0 "Total amount:"
                <+> integerAmountDoc unit (detailedTxAmount s)
          else
              mempty]
           <>
             fmap (addrFormat id) (Map.assocs $ Map.map fst detailedTxInbound)’
    |
232 |             fmap (addrFormat id) (Map.assocs $ Map.map fst detailedTxInbound)
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:234:31: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘Address -> Maybe Data.Text.Internal.Text’
    • Probable cause: ‘addrToString’ is applied to too few arguments
      In the second argument of ‘($)’, namely ‘addrToString a’
      In the first argument of ‘addressDoc’, namely
        ‘(textDoc $ addrToString a)’
      In the first argument of ‘(<>)’, namely
        ‘addressDoc (textDoc $ addrToString a)’
    |
234 |         addressDoc (textDoc $ addrToString a) <> colon <+>
    |                               ^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:308:44: error:
    • Couldn't match type ‘Address’ with ‘Network’
      Expected type: [(Network, Satoshi)]
        Actual type: [(Address, Satoshi)]
    • In the second argument of ‘fmap’, namely
        ‘(Map.assocs detailedTxOutbound)’
      In the first argument of ‘(<>)’, namely
        ‘fmap addrFormatOutbound (Map.assocs detailedTxOutbound)’
      In the second argument of ‘($)’, namely
        ‘fmap addrFormatOutbound (Map.assocs detailedTxOutbound)
           <> [nonStdRcp]’
    |
308 |                   fmap addrFormatOutbound (Map.assocs detailedTxOutbound) <>
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:328:19: error:
    • Couldn't match type ‘Address’ with ‘Network’
      Expected type: [(Network, (Satoshi, Maybe SoftPath))]
        Actual type: [(Address, (Satoshi, Maybe SoftPath))]
    • In the second argument of ‘($)’, namely
        ‘sortOn (((not . isExternal) <$>) . snd . snd)
           $ Map.assocs detailedTxInbound’
      In the second argument of ‘($)’, namely
        ‘fmap addrFormatInbound
           $ sortOn (((not . isExternal) <$>) . snd . snd)
               $ Map.assocs detailedTxInbound’
      In the second argument of ‘($)’, namely
        ‘vcat
           $ fmap addrFormatInbound
               $ sortOn (((not . isExternal) <$>) . snd . snd)
                   $ Map.assocs detailedTxInbound’
    |
328 |                   sortOn (((not . isExternal) <$>) . snd . snd) $
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Network/Haskoin/Wallet/DetailedTx.hs:337:51: error:
    • Couldn't match type ‘Address’ with ‘Network’
      Expected type: [(Network, (Satoshi, Maybe SoftPath))]
        Actual type: [(Address, (Satoshi, Maybe SoftPath))]
    • In the second argument of ‘fmap’, namely
        ‘(Map.assocs detailedTxMyInputs)’
      In the second argument of ‘($)’, namely
        ‘fmap addrFormatMyInputs (Map.assocs detailedTxMyInputs)’
      In the second argument of ‘($)’, namely
        ‘vcat $ fmap addrFormatMyInputs (Map.assocs detailedTxMyInputs)’
    |
337 |                   vcat $ fmap addrFormatMyInputs (Map.assocs detailedTxMyInputs)
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:346:47: error:
    • Couldn't match type ‘Address’ with ‘Network’
      Expected type: [(Network, Satoshi)]
        Actual type: [(Address, Satoshi)]
    • In the second argument of ‘fmap’, namely
        ‘(Map.assocs detailedTxOtherInputs)’
      In the second argument of ‘($)’, namely
        ‘fmap addrFormatOtherInputs (Map.assocs detailedTxOtherInputs)’
      In the second argument of ‘($)’, namely
        ‘vcat
           $ fmap addrFormatOtherInputs (Map.assocs detailedTxOtherInputs)’
    |
346 |                   fmap addrFormatOtherInputs (Map.assocs detailedTxOtherInputs)
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:355:24: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘Address -> Maybe Data.Text.Internal.Text’
    • Probable cause: ‘addrToString’ is applied to too few arguments
      In the second argument of ‘($)’, namely ‘addrToString a’
      In the second argument of ‘($)’, namely ‘textDoc $ addrToString a’
      In the third argument of ‘addrValDoc’, namely
        ‘((if maybe False isExternal pM then
               addressDoc
           else
               internalAddressDoc)
            $ textDoc $ addrToString a)’
    |
355 |              textDoc $ addrToString a)
    |                        ^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:362:45: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘Address -> Maybe Data.Text.Internal.Text’
    • Probable cause: ‘addrToString’ is applied to too few arguments
      In the second argument of ‘($)’, namely ‘addrToString a’
      In the second argument of ‘($)’, namely ‘textDoc $ addrToString a’
      In the third argument of ‘addrValDoc’, namely
        ‘(internalAddressDoc $ textDoc $ addrToString a)’
    |
362 |             (internalAddressDoc $ textDoc $ addrToString a)
    |                                             ^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:369:45: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘Address -> Maybe Data.Text.Internal.Text’
    • Probable cause: ‘addrToString’ is applied to too few arguments
      In the second argument of ‘($)’, namely ‘addrToString a’
      In the second argument of ‘($)’, namely ‘textDoc $ addrToString a’
      In the third argument of ‘addrValDoc’, namely
        ‘(internalAddressDoc $ textDoc $ addrToString a)’
    |
369 |             (internalAddressDoc $ textDoc $ addrToString a)
    |                                             ^^^^^^^^^^^^^^

src/Network/Haskoin/Wallet/DetailedTx.hs:376:37: error:
    • Couldn't match expected type ‘Data.Text.Internal.Text’
                  with actual type ‘Address -> Maybe Data.Text.Internal.Text’
    • Probable cause: ‘addrToString’ is applied to too few arguments
      In the second argument of ‘($)’, namely ‘addrToString a’
      In the second argument of ‘($)’, namely ‘textDoc $ addrToString a’
      In the third argument of ‘addrValDoc’, namely
        ‘(addressDoc $ textDoc $ addrToString a)’
    |
376 |             (addressDoc $ textDoc $ addrToString a)
    |                                     ^^^^^^^^^^^^^^
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
haskoin-wallet-0.6.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by m0dev76** [comment]
Hey @gabin22, thanks for submitting a bug report. I'd recommend not to use or work with the code in master at the moment. I'm in the middle of a big cleanup and rewrite in branch no-foundation. The new code will also work nicely with the new haskoin-store designed by @jprupp . I'll merge that to master when it's done.

**Comment by jprupp** [comment]
Use the `no-foundation` branch. we'll merge it to master soon.
